=begin
Lista de Usuários

Essa API provê o acesso aos usuários do sistema 

OpenAPI spec version: 1.0.0
Contact: gabriellemaximo12@gmail.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class User < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :email

end
