=begin
Lista de Usuários

Essa API provê o acesso aos usuários do sistema 

OpenAPI spec version: 1.0.0
Contact: gabriellemaximo12@gmail.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "error".pluralize.to_sym, id: false do |t|
      t.integer :code
      t.string :message

      t.timestamps
    end

    create_table "user".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :name
      t.string :email

      t.timestamps
    end

  end
end
