=begin
Lista de Usuários

Essa API provê o acesso aos usuários do sistema 

OpenAPI spec version: 1.0.0
Contact: gabriellemaximo12@gmail.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class UsersController < ApplicationController

  def index
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def destroy
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def show
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def users_patch
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def users_put
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
